# interfaces.py
from abc import ABC, abstractmethod


class IRobot(ABC):
    @abstractmethod
    def move(self, distance: float) -> None: ...
    @abstractmethod
    def turn(self, degrees: int) -> None: ...
    @abstractmethod
    def set(self, mode: str) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...


class IRobotAPI(ABC):
    @abstractmethod
    def move(self, distance: int) -> None: ...
    @abstractmethod
    def turn(self, angle: int) -> None: ...
    @abstractmethod
    def set_mode(self, mode: str) -> None: ...
    @abstractmethod
    def start(self) -> None: ...
    @abstractmethod
    def stop(self) -> None: ...